project:
  type: website
  output-dir: docs

website:
  title: ""
  sidebar:
    contents:
      - text: "Inicio"
        href: index.qmd
      - text: "Algoritmos O grande"
        href: exp_1.qmd
      - text: "Estructura de Datos"
        href: exp_2.qmd

format:
  html:
    theme: default
    css: styles.css
    toc: true
    toc-location: left
    toc-title: "Contenido"

